-- Initial values combine Tag_Taxonomy_with_Descriptions.xlsx with the values
-- already used by Final_Template_Tag_Mapping_Business_Review v1.0.xlsx.
-- Descriptions absent from both approved inputs remain NULL.
INSERT INTO iic_msg_tag_value (group_code, tag_code, tag_name, description, sort_order)
VALUES ('CONTENT_TYPE', 'CONTENT_TYPE_EMAIL', 'Email', 'Standard email communication', 10),
       ('CONTENT_TYPE', 'CONTENT_TYPE_VIDEO', 'Video', 'Video-based content', 20),
       ('CONTENT_TYPE', 'CONTENT_TYPE_INFOGRAPHIC', 'Infographic', 'Visual informational content', 30),
       ('TRIGGER', 'TRIGGER_BIRTHDAY', 'Birthday', 'Client birthday communication trigger', 10),
       ('TRIGGER', 'TRIGGER_MARRIAGE', 'Marriage', 'Client marriage life event', 20),
       ('TRIGGER', 'TRIGGER_BIRTH_NEW_CHILD', 'Birth / New Child', 'New child life event', 30),
       ('TRIGGER', 'TRIGGER_RETIREMENT', 'Retirement', 'Client retirement milestone', 40),
       ('TRIGGER', 'TRIGGER_ANNUAL_REVIEW', 'Annual Review', 'Scheduled annual financial review', 50),
       ('TRIGGER', 'TRIGGER_TAX_SEASON', 'Tax Season', 'Tax period engagement', 60),
       ('TRIGGER', 'TRIGGER_FESTIVE_SEASON', 'Festive Season', 'End-of-year seasonal communication', 70),
       ('TRIGGER', 'TRIGGER_ADVISER_ACTIVITY', 'Adviser Activity', NULL, 80),
       ('TRIGGER', 'TRIGGER_AWARENESS_MONTHS', 'Awareness Months', NULL, 90),
       ('TRIGGER', 'TRIGGER_DEATH_BEREAVEMENT', 'Death / Bereavement', NULL, 100),
       ('TRIGGER', 'TRIGGER_FATHERS_DAY', 'Father’s Day', NULL, 110),
       ('TRIGGER', 'TRIGGER_NEW_ADVISER_INTRODUCTION', 'New Adviser Introduction', NULL, 120),
       ('TRIGGER', 'TRIGGER_SPECIAL_OFFER', 'Special Offer', NULL, 130),
       ('LIFECYCLE_STAGE', 'LIFECYCLE_STAGE_PROSPECT', 'Prospect', 'Potential new client', 10),
       ('LIFECYCLE_STAGE', 'LIFECYCLE_STAGE_EXISTING_CLIENT', 'Existing Client', 'Current client', 20),
       ('LIFECYCLE_STAGE', 'LIFECYCLE_STAGE_RETENTION', 'Retention', 'Client retention focus', 30),
       ('LIFECYCLE_STAGE', 'LIFECYCLE_STAGE_NEW_CLIENT', 'New Client', NULL, 40),
       ('LIFECYCLE_STAGE', 'LIFECYCLE_STAGE_REVIEW', 'Review', NULL, 50),
       ('FINANCIAL_NEED', 'FINANCIAL_NEED_PROTECT', 'Protect', 'Insurance and risk protection needs', 10),
       ('FINANCIAL_NEED', 'FINANCIAL_NEED_GROW_WEALTH', 'Grow Wealth', 'Investment and wealth growth', 20),
       ('FINANCIAL_NEED', 'FINANCIAL_NEED_SAVE', 'Save', 'Savings and short-term goals', 30),
       ('FINANCIAL_NEED', 'FINANCIAL_NEED_AWARENESS', 'Awareness', NULL, 40),
       ('FINANCIAL_NEED', 'FINANCIAL_NEED_ENGAGEMENT', 'Engagement', NULL, 50),
       ('FINANCIAL_NEED', 'FINANCIAL_NEED_FINANCIAL_EDUCATION', 'Financial Education', NULL, 60),
       ('FINANCIAL_NEED', 'FINANCIAL_NEED_MANAGE_LIFE_CHANGES', 'Manage Life Changes', NULL, 70),
       ('FINANCIAL_NEED', 'FINANCIAL_NEED_PLAN_RETIREMENT', 'Plan Retirement', NULL, 80),
       ('PROPOSITION_SOURCE', 'PROPOSITION_SOURCE_OM_BANK', 'OM Bank', 'OM Bank offering related', 10),
       ('PROPOSITION_SOURCE', 'PROPOSITION_SOURCE_REWARDS', 'Rewards', 'Rewards programme related', 20)
ON DUPLICATE KEY UPDATE group_code = VALUES(group_code), tag_name = VALUES(tag_name), description = VALUES(description), sort_order = VALUES(sort_order);
